"""Tier 2: realized calibration check (75-80% predicted-P bucket overconfidence).

The complement to predicted_vs_realized.py. That check detects DRIFT in the
gap between predicted and realized P over time. This check detects the
ABSOLUTE LEVEL of miscalibration in the 75-80% bucket — where most prod
picks land — vs realized hit rates.

**Attribution fix 2026-05-01**: previously used streak ``result`` as proxy
for primary-pick hit. That's biased on double-down days because streak
"hit" requires BOTH picks to hit, so a DD pick that did hit gets attributed
as "miss" whenever the primary missed. The fix: when ``data_dir`` is
provided, look up the actual per-pick day-hit from the season's PA frame.
The biased path remains as a safety fallback when pa frame isn't available.

The corrected attribution shows real over-confidence is ~+6.6pp overall
and ~+12.3pp in the [0.75, 0.80) bucket — **less alarming than the
proxy-based "+14pp" finding from 2026-04-29**, which was inflated by the
DD attribution bias. Thresholds are recalibrated accordingly.

Severity ladder (75-80% bucket only; other buckets ignored):
  predicted - realized < 8pp:     no alert (well-calibrated under proper attribution)
  >= 8pp:                         INFO  (worth observing)
  >= 15pp:                        WARN  (significantly overconfident)
  >= 25pp:                        CRITICAL (true distribution-shift signal)

Lookback window: last 30 days. Minimum bucket count: 5 picks.
"""

from __future__ import annotations

import json
import logging
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

from bts.health.alert import Alert

log = logging.getLogger(__name__)

SOURCE = "realized_calibration"

DEFAULT_THRESHOLDS = {
    "info_pp": 8.0,
    "warn_pp": 15.0,
    "critical_pp": 25.0,
    "lookback_days": 30,
    "min_bucket_n": 5,
    "bucket_low": 0.75,
    "bucket_high": 0.80,
}


def _build_day_hit_lookup(data_dir: Path, today: date, lookback_days: int) -> dict:
    """Build (batter_id, date) -> day_had_any_hit lookup from current season's PA frame.

    Returns empty dict if no parquet exists; caller falls back to streak-result proxy.
    """
    try:
        import pandas as pd
    except ImportError:
        return {}
    # Local import: build.py imports pandas at module level, so importing it lazily here
    # preserves this function's graceful pandas-absent degradation above.
    from bts.data.build import read_pa_for_bts_scoring
    cutoff = today - timedelta(days=lookback_days)
    candidates = [data_dir / f"pa_{y}.parquet" for y in (today.year, today.year - 1)]
    parts = []
    for p in candidates:
        if p.exists():
            try:
                parts.append(read_pa_for_bts_scoring(p, ["batter_id", "date", "is_hit"]))
            except Exception as e:
                log.warning(f"failed to load {p} for calibration attribution: {e}")
    if not parts:
        return {}
    pa_df = pd.concat(parts, ignore_index=True)
    pa_df["date"] = pd.to_datetime(pa_df["date"]).dt.date
    pa_df = pa_df[(pa_df["date"] >= cutoff) & (pa_df["date"] <= today)]
    daily = (
        pa_df.groupby(["batter_id", "date"])["is_hit"]
        .max()
        .reset_index()
    )
    return {(int(r["batter_id"]), r["date"]): int(r["is_hit"]) for _, r in daily.iterrows()}


def _current_deploy_iso(repo_dir: Path) -> str | None:
    """Return the ISO timestamp the current model was DEPLOYED, or None.

    Used to filter out picks generated by older model iterations. Picks before
    the current deploy can't be pooled with current-model picks for calibration
    (per project_bts_production_realized_contaminated.md).

    Prefers `data/.last_deploy_iso` — a wall-clock stamp written by the deploy
    workflow on every deploy/rollback. It is monotonic, so it fixes both
    commit-time≠deploy-time and the canary-rollback-moves-HEAD's-date-backward
    case. Falls back to HEAD's git commit time (`%cI`) when the stamp is absent
    (older boxes / local runs) — approximate, but no worse than before.
    """
    stamp = Path(repo_dir) / "data" / ".last_deploy_iso"
    try:
        val = stamp.read_text().strip()
        if val:
            return val
    except OSError:
        pass
    import subprocess
    try:
        out = subprocess.check_output(
            ["git", "-C", str(repo_dir), "log", "-1", "--format=%cI", "HEAD"],
            stderr=subprocess.PIPE, text=True, timeout=5,
        ).strip()
        return out or None
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _iso_before(run_time: str, since_deploy_iso: str) -> bool:
    """True if instant ``run_time`` is strictly before ``since_deploy_iso``.

    Compares timezone-aware datetimes, NOT ISO strings: run_time is written in
    +00:00 while ``since_deploy_iso`` (git %cI) carries the committer's local
    offset, so a lexicographic compare misclassifies picks whenever the offsets
    differ. Unparseable run_time → treated as pre-deploy (conservative skip).
    A naive timestamp is assumed UTC.
    """
    try:
        rt = datetime.fromisoformat(run_time)
        dep = datetime.fromisoformat(since_deploy_iso)
    except (ValueError, TypeError):
        return True
    if rt.tzinfo is None:
        rt = rt.replace(tzinfo=timezone.utc)
    if dep.tzinfo is None:
        dep = dep.replace(tzinfo=timezone.utc)
    return rt < dep


def _regime_fingerprint(body: dict) -> tuple | None:
    """Production-regime identity of a pick, or None if unstamped.

    (model_pickle_sha256, policy_npz_sha256, feature_env_hash) — the stamps
    every pick file carries since provenance v1. Two picks with the same
    fingerprint were produced by byte-identical model + policy + feature env,
    so pooling them for calibration is valid REGARDLESS of deploys in between
    (audit F6: wall-clock deploy resets erased the sample on docs/shadow/ops
    deploys — 11 in 10 days — leaving min_bucket_n unreachable)."""
    fp = (
        body.get("model_pickle_sha256"),
        body.get("policy_npz_sha256"),
        body.get("feature_env_hash"),
    )
    return fp if all(fp) else None


def check(
    picks_dir: Path,
    today: date | None = None,
    thresholds: dict | None = None,
    data_dir: Path | None = None,
    since_deploy_iso: str | None = None,
) -> list[Alert]:
    """Returns INFO/WARN/CRITICAL alert when 75-80% bucket is overconfident.

    When ``data_dir`` is provided AND the season parquet exists, uses true
    per-pick day-hit attribution. Otherwise falls back to streak-result
    proxy (biased on DD days; preserved for backward compatibility).

    Pooling (audit F6): picks are pooled by production-REGIME fingerprint
    (model/policy/feature-env hashes stamped on every pick) — the pool is all
    in-window picks matching the newest stamped pick's fingerprint. Deploys
    that don't change the regime (docs/shadow/ops) no longer reset the sample;
    a genuine model/policy/env change still does. ``since_deploy_iso`` is the
    FALLBACK filter for unstamped (pre-provenance) pick sets: it drops picks
    whose ``run_time`` predates the current deploy (see
    project_bts_production_realized_contaminated.md). With neither available,
    the legacy unfiltered behavior applies — noise, not signal, on a
    long-running project.
    """
    t = {**DEFAULT_THRESHOLDS, **(thresholds or {})}
    if today is None:
        today = date.today()
    if not picks_dir.exists():
        return []

    # Build proper attribution lookup if PA frame is available.
    day_hit_lookup = {}
    if data_dir is not None:
        day_hit_lookup = _build_day_hit_lookup(data_dir, today, t["lookback_days"])
    using_pa_attribution = bool(day_hit_lookup)

    cutoff = today - timedelta(days=t["lookback_days"])
    in_bucket: list[tuple[float, int]] = []
    skipped_pre_deploy = 0
    skipped_other_regime = 0
    try:
        files = sorted(picks_dir.glob("*.json"))
    except OSError as e:
        log.warning(f"could not list {picks_dir}: {e}")
        return []
    candidates: list[tuple[date, dict]] = []
    for f in files:
        if f.name.startswith("._"):
            continue
        if ".shadow." in f.name or "scheduler" in f.name or "streak" in f.name:
            continue
        try:
            body = json.loads(f.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError, OSError):
            continue
        try:
            pick_date = date.fromisoformat(body.get("date", ""))
        except (ValueError, TypeError):
            continue
        if pick_date < cutoff or pick_date > today:
            continue
        candidates.append((pick_date, body))

    # Audit F6: pool by production-regime fingerprint when available. The
    # current regime = the fingerprint of the newest stamped pick; only picks
    # from that regime pool together, so a no-regime-change deploy (docs,
    # shadow, ops) no longer erases the accumulated sample, while a genuine
    # model/policy/feature-env change still resets it. Unstamped (pre-
    # provenance) pick sets fall back to the wall-clock deploy filter.
    current_regime = None
    for _, body in sorted(candidates, key=lambda c: c[0]):
        fp = _regime_fingerprint(body)
        if fp is not None:
            current_regime = fp

    for pick_date, body in candidates:
        if current_regime is not None:
            if _regime_fingerprint(body) != current_regime:
                skipped_other_regime += 1
                continue
        elif since_deploy_iso is not None:
            run_time = body.get("run_time", "")
            if not run_time or _iso_before(run_time, since_deploy_iso):
                skipped_pre_deploy += 1
                continue
        result = body.get("result")
        if result not in ("hit", "miss"):
            continue
        slot_results = body.get("slot_results") or {}
        # Iterate primary + double_down so both picks contribute to the bucket
        # under the proper PA-frame attribution path. The biased fallback path
        # uses primary-only because streak result misattributes DD picks.
        for slot_key in ("pick", "double_down"):
            if slot_results.get(slot_key) == "void":
                continue
            slot = body.get(slot_key) or {}
            p = slot.get("p_game_hit")
            if p is None:
                continue
            if not (t["bucket_low"] <= p < t["bucket_high"]):
                continue
            if using_pa_attribution:
                bid = slot.get("batter_id")
                if bid is None:
                    continue  # PA-frame join needs batter_id
                day_hit = day_hit_lookup.get((int(bid), pick_date))
                if day_hit is None:
                    continue  # late data; skip rather than guess
                in_bucket.append((float(p), int(day_hit)))
            else:
                # Biased fallback: streak result. Only trustworthy for primary picks
                # (and only on primary-only days at that — but DD-presence isn't
                # checked here; this is the legacy path before the PA-frame fix).
                if slot_key == "pick":
                    in_bucket.append((float(p), 1 if result == "hit" else 0))

    if len(in_bucket) < t["min_bucket_n"]:
        return []

    mean_predicted = sum(p for p, _ in in_bucket) / len(in_bucket)
    realized_rate = sum(h for _, h in in_bucket) / len(in_bucket)
    overconf_pp = (mean_predicted - realized_rate) * 100

    if overconf_pp < t["info_pp"]:
        return []
    if overconf_pp >= t["critical_pp"]:
        level = "CRITICAL"
    elif overconf_pp >= t["warn_pp"]:
        level = "WARN"
    else:
        level = "INFO"

    attribution = "pa-frame" if using_pa_attribution else "streak-proxy (biased on DD days)"
    if current_regime is not None:
        deploy_filter = (
            f"regime-fingerprint (skipped {skipped_other_regime} other-regime)"
        )
    elif since_deploy_iso:
        deploy_filter = (
            f"since-deploy={since_deploy_iso[:10]} (skipped {skipped_pre_deploy} pre-deploy)"
        )
    else:
        deploy_filter = "ALL-PICKS (iteration-contaminated)"
    msg = (
        f"75-80% bucket overconfident by {overconf_pp:+.1f}pp over last "
        f"{t['lookback_days']}d (n={len(in_bucket)}, predicted {mean_predicted:.3f}, "
        f"realized {realized_rate:.3f}, attribution={attribution}, filter={deploy_filter})"
    )
    if level == "CRITICAL":
        msg += ". Real current-model overconfidence signal — investigate distribution shift."
    return [Alert(level=level, source=SOURCE, message=msg)]
